# Generated by Django 5.1.1 on 2024-10-06 13:00

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Documento')),
                ('nro_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Documento')),
                ('nombre', models.CharField(help_text='Ingrese su nombre', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Ingrese su apellido', max_length=50, verbose_name='Apellido')),
                ('edad', models.IntegerField(blank=True, help_text='Ingrese su edad', null=True, verbose_name='Edad')),
                ('telefono', models.CharField(blank=True, default='+5691324567', help_text='Ingrese su telefono', max_length=15, null=True, verbose_name='Telefono')),
                ('direccion', models.CharField(help_text='Ingrese su direccion', max_length=50, verbose_name='Direccion')),
                ('ciudad', models.CharField(help_text='Ingrese su ciudad', max_length=50, verbose_name='Ciudad')),
                ('pais', django_countries.fields.CountryField(max_length=2, verbose_name='Pais')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
